[package]
name = "dstream"
version = "0.0.1"
authors = [ "Octavian Geagla <ogeagla@gmail.com>" ]

[dependencies]
nalgebra = "0.11.2"
num = "0.1.37"
itertools = "0.6.0"
petgraph = "0.4.4"
rand = "0.3.14"